/**
 * Mock Replay Data — 专家对比复盘时间线示例数据
 *
 * 模拟一次"SMTX OS 集群脑裂故障排查"场景的玩家复盘
 */

import type { ReplayData } from '@skillquest/types';

export const MOCK_REPLAY_DATA: ReplayData = {
  summary: {
    userTime: 1080,   // 18分钟
    expertTime: 540,   // 9分钟
    score: 62,
    slaLoss: '99.99% → 99.91%',
  },
  playerSteps: [
    {
      id: 'p1',
      timestamp: 0,
      actionName: '查看集群告警面板',
      status: 'correct',
      description: '玩家首先检查了 CloudTower 的告警页面，发现 ZBS 存储服务异常。',
      impactScore: 0,
      sourceQuote: '当集群出现异常告警时，应首先通过 CloudTower 确认告警类型和影响范围。',
      worldStateSnapshot: { phase: 'initial', nodesOnline: 3, slaPercent: 99.99 },
    },
    {
      id: 'p2',
      timestamp: 60,
      actionName: '检查网络连通性',
      status: 'correct',
      description: '使用 ping 和 traceroute 验证管理网络和存储网络的可达性。',
      impactScore: 0,
      sourceQuote: 'ZBS 依赖管理网络和存储网络通信，排查应优先确认网络层健康状态。',
      worldStateSnapshot: { phase: 'diagnosis', nodesOnline: 3, slaPercent: 99.99 },
    },
    {
      id: 'p3',
      timestamp: 180,
      actionName: '直接重启 Node-2',
      status: 'error',
      description: '玩家未进一步定位故障原因，直接选择重启疑似故障节点 Node-2。',
      impactScore: -35,
      deviationNotice: '未确认 ZooKeeper 仲裁状态就重启节点，可能导致集群丧失 quorum，触发脑裂风险。',
      sourceQuote: '在执行任何节点重启操作前，必须先确认 ZooKeeper 集群的 quorum 状态，确保多数派存活。',
      worldStateSnapshot: { phase: 'risky-action', nodesOnline: 2, slaPercent: 99.95 },
    },
    {
      id: 'p4',
      timestamp: 300,
      actionName: '等待 Node-2 重启完成',
      status: 'warning',
      description: 'Node-2 重启耗时较长，期间存储 IO 延迟持续攀升。',
      impactScore: -15,
      deviationNotice: '此等待期间未采取任何缓解措施（如迁移热数据），导致业务持续受损。',
      worldStateSnapshot: { phase: 'degraded', nodesOnline: 2, slaPercent: 99.93 },
    },
    {
      id: 'p5',
      timestamp: 540,
      actionName: '发现 ZooKeeper quorum 丢失',
      status: 'error',
      description: 'Node-2 重启后 ZooKeeper 未自动恢复，集群进入脑裂状态！',
      impactScore: -40,
      deviationNotice: '由于此处选择重启节点，导致了 300GB 数据的重新同步，产生了 25 分钟的业务延迟。这是灾难性操作的直接后果。',
      sourceQuote: '脑裂 (Split-Brain) 是分布式存储最严重的故障之一，会导致数据不一致和业务中断。',
      worldStateSnapshot: { phase: 'split-brain', nodesOnline: 2, slaPercent: 99.50 },
    },
    {
      id: 'p6',
      timestamp: 720,
      actionName: '手动恢复 ZooKeeper',
      status: 'warning',
      description: '尝试手动重建 ZooKeeper 集群，但操作步骤不完整。',
      impactScore: -5,
      deviationNotice: '手动恢复时遗漏了 leader election 验证步骤，导致恢复后仍有隐患。',
      worldStateSnapshot: { phase: 'recovering', nodesOnline: 3, slaPercent: 99.60 },
    },
    {
      id: 'p7',
      timestamp: 900,
      actionName: '触发数据一致性校验',
      status: 'correct',
      description: '执行 ZBS 数据一致性检查，确认无数据损坏。',
      impactScore: 0,
      worldStateSnapshot: { phase: 'verification', nodesOnline: 3, slaPercent: 99.80 },
    },
    {
      id: 'p8',
      timestamp: 1080,
      actionName: '恢复业务并提交报告',
      status: 'correct',
      description: '确认集群状态正常后，恢复 VM 业务并提交事故报告。',
      impactScore: 0,
      worldStateSnapshot: { phase: 'resolved', nodesOnline: 3, slaPercent: 99.91 },
    },
  ],
  expertSteps: [
    {
      id: 'e1',
      timestamp: 0,
      actionName: '查看集群告警面板',
      status: 'correct',
      description: '首先通过 CloudTower 确认告警类型：ZBS 存储服务异常。',
      impactScore: 0,
      worldStateSnapshot: { phase: 'initial' },
    },
    {
      id: 'e2',
      timestamp: 60,
      actionName: '检查网络连通性',
      status: 'correct',
      description: '验证管理网络和存储网络的连通性，排除网络层问题。',
      impactScore: 0,
      worldStateSnapshot: { phase: 'diagnosis' },
    },
    {
      id: 'e3',
      timestamp: 120,
      actionName: '检查 ZooKeeper quorum 状态',
      status: 'correct',
      description: '关键步骤：使用 zkCli 确认 ZooKeeper 集群 quorum 仍然存活（2/3 节点正常）。',
      impactScore: 0,
      sourceQuote: 'ZooKeeper 要求多数派存活才能正常工作。3 节点集群至少需要 2 个节点在线。',
      worldStateSnapshot: { phase: 'deep-diagnosis' },
    },
    {
      id: 'e4',
      timestamp: 180,
      actionName: '定位 ZBS Chunk Server 异常',
      status: 'correct',
      description: '通过日志分析发现 Node-2 的 Chunk Server 进程 OOM，并非硬件故障。',
      impactScore: 0,
      worldStateSnapshot: { phase: 'root-cause' },
    },
    {
      id: 'e5',
      timestamp: 240,
      actionName: '热迁移关键 VM 至健康节点',
      status: 'correct',
      description: '在修复前，先将 Node-2 上的关键 VM 实时迁移到其他节点，保障业务零中断。',
      impactScore: 0,
      worldStateSnapshot: { phase: 'mitigation' },
    },
    {
      id: 'e6',
      timestamp: 360,
      actionName: '重启 Chunk Server 进程',
      status: 'correct',
      description: '仅重启故障进程而非整个节点，最小化影响范围。调整内存限制防止再次 OOM。',
      impactScore: 0,
      sourceQuote: '优先重启服务进程而非节点。节点重启会导致 ZooKeeper 成员变更，可能影响 quorum。',
      worldStateSnapshot: { phase: 'targeted-fix' },
    },
    {
      id: 'e7',
      timestamp: 420,
      actionName: '验证集群状态与数据一致性',
      status: 'correct',
      description: '全量验证 ZBS 副本一致性，确认无数据丢失，所有节点状态正常。',
      impactScore: 0,
      worldStateSnapshot: { phase: 'verification' },
    },
    {
      id: 'e8',
      timestamp: 540,
      actionName: '将 VM 迁回并提交报告',
      status: 'correct',
      description: '恢复原始 VM 分布，提交事故报告，SLA 保持 99.99%。',
      impactScore: 0,
      worldStateSnapshot: { phase: 'resolved' },
    },
  ],
};
